global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'filestats'
    static_configs:
      - targets: ['filestat_exporter:9943']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'patterns'
    static_configs:
      - targets: ['pattern_watcher:9944']