- name: Get latest release of {{ item.package }}
  community.general.github_release:
    user: "{{ item.repo }}"
    repo: "{{ item.package }}"
    action: latest_release
  register: release
- name: Download {{ item.package }}
  ansible.builtin.unarchive:
    src: "{{ item.base_url }}/releases/download/{{ release.tag }}/{{ item.package }}-{{ release.tag[1:] }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
- name: Install {{ item.package }}
  ansible.builtin.copy:
    src: "/tmp/{{ item.package }}-{{ release.tag[1:] }}.linux-amd64/{{ item.package }}"
    dest: "/usr/local/bin"
    mode: a+x
  become: true
- name: install systemd files
  ansible.builtin.copy:
    src: "systemd-services/{{ item.package }}.service"
    dest: "/etc/systemd/system/{{ item.package }}.service"
- name: Create config directory
  ansible.builtin.file:
    path: /etc/{{ item.package }}
    state: directory
    mode: '0755'
- name: add configs
  ansible.builtin.template:
    src: templates/etc/{{ item.package }}/{{ item.package }}.yaml.j2
    dest: /etc/{{ item.package }}/{{ item.package }}.yaml
- name: Enable and {{ item.package }}
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    name: "{{ item.package }}"
    enabled: yes